services:
  - type: web
    name: comp2537-assignment1
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_USER
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: MONGODB_HOST
        sync: false
      - key: MONGODB_DATABASE
        sync: false
      - key: MONGODB_SESSION_SECRET
        sync: false
      - key: NODE_SESSION_SECRET
        sync: false